### ISSUE TITLE
Max-Width for CodeMirror?

### ISSUE THREAD

**Issue by xu-chris** [JonasDoebertin/kirby-visual-markdown#1]
I like the fullscreen so much. But on my 34" 21:9 display it looks a bit weird:
![bildschirmfoto 2015-03-31 um 12 58 57](https://cloud.githubusercontent.com/assets/980778/6917605/670b1c94-d7a6-11e4-9e98-736c1d7e5353.png)

I wish to have something like iAWriter has: 
![bildschirmfoto 2015-03-31 um 13 00 18](https://cloud.githubusercontent.com/assets/980778/6917622/84d1275a-d7a6-11e4-8bad-6b3de975d806.png)

I've tried to add a max-width to the CodeMirror window which looks now like this:
![bildschirmfoto 2015-03-31 um 13 06 17](https://cloud.githubusercontent.com/assets/980778/6917674/fc65773a-d7a6-11e4-857b-98631db34b92.png)

Maybe you have to add a class to the body on Fullscreen which gives it some extra CSS styles to the CodeMirror?

**Comment by JonasDoebertin** [comment]
I just pushed a new release with some improvements for the fullscreen mode: [v1.0.1](https://github.com/JonasDoebertin/kirby-visual-markdown/releases/tag/1.0.1)
