### ISSUE TITLE
Filenames with underscores show up as italic

### ISSUE THREAD

**Issue by samnabi** [JonasDoebertin/kirby-visual-markdown#11]
A little quirk I noticed: a filename containing underscores will make the rest of the line italic. 

Perhaps disabling the markdown preview within Kirbytags makes sense?

![screenshot 2015-04-11 15 01 56](https://cloud.githubusercontent.com/assets/1731536/7102830/0c58d20e-e05d-11e4-8a7a-6ff6b7c853d0.png)

**Comment by JonasDoebertin** [comment]
Thanks for pointing that out! Will be fixed in the next release!

**Comment by JonasDoebertin** [comment]
Fixed in the [1.2.0-beta.1](https://github.com/JonasDoebertin/kirby-visual-markdown/releases/tag/1.2.0-beta.1) release.

**Comment by samnabi** [comment]
Looking good, thanks!
