### ISSUE TITLE
Markdown syntax toggle

### ISSUE THREAD

**Issue by malvese** [JonasDoebertin/kirby-visual-markdown#15]
This is an idea rather than an issue.

I thought about a toggle to display/hide the Markdown syntax. It would be a button in the toolbar, possibly to the right next to the fullscreen button, to avoid confusion with _editing_ buttons.
The result would be a hybrid editor: if you want to type Markdown formatting you can ; if the syntax bugs you, just hide it and only use the toolbar buttons.

Fiddling in Dev Tools:

![markdownhide](https://cloud.githubusercontent.com/assets/193492/7183804/d52c9e0e-e459-11e4-8d2e-98e8c4cdfdf9.gif)

There a a number of issues with my quick test:
- titles have to be aligned in a different way than they are right now (I gave an absolute position to the `#` inside the title wrapper, but then the cursor is at the wrong place)
- lists have to keep some kind of bullets, here I just applied a dumb `.cm-formatting {display: none}`. Same for HRs, and probably other elements, so we'd need to target more specific classes like `.cm-header`.

So far, I believe the toggle could be a matter of simply applying alternate styles. Perhaps just add a class to the CodeMirror wrapper.

**Comment by xypaul** [comment]
I like this idea :+1:

**Comment by dgdsp** [comment]
+1

**Comment by malvese** [comment]
The just realeased [TextNut editor](Switch between Markdown and rich text editing on-the-fly) has such a "Switch between Markdown and rich text editing on-the-fly".
But it has no buttons so it feels a bit weird. Or for purists. If you're like me and can never remember the link syntax, it won't help ^_^

**Comment by JonasDoebertin** [comment]
Not 100% sure how this can be solved with CodeMirror.

I guess it would be possible to have a "preview mode" that simply toggles / applies some different styles. I'll see what I can do about it.

I don't know a way to add image previews etc. like Ulysses  and TextNut do with CodeMirror, though.

**Comment by malvese** [comment]
Yes, simply switching styles is what I had in mind. It's enough to make the editor look a bit closer to the rendered content. Images and other features are a totally different topic.
