### ISSUE TITLE
Alt + Enter to save

### ISSUE THREAD

**Issue by medienbaecker** [JonasDoebertin/kirby-visual-markdown#17]
The markdown editor somehow doesn't allow to hit ALT + Enter as a shortcut to the "save"-button. The normal fields do.

![alt enter](https://cloud.githubusercontent.com/assets/7975568/7196462/9ae29da6-e4d2-11e4-81c4-8b0474a97cf5.gif)

**Comment by JonasDoebertin** [comment]
Fixed with 3a825a60a7a7cd3f026c1156bde13657f8d745a6.

`Alt + Enter` and `Command + Enter` now trigger a panel page save.
