### ISSUE TITLE
HTML tags break the syntax highlighting

### ISSUE THREAD

**Issue by medienbaecker** [JonasDoebertin/kirby-visual-markdown#18]
Adding HTML tags like "br" or "sup" will break the following syntax highlighting. 

![0daa8a36e76c4f8a](https://cloud.githubusercontent.com/assets/7975568/7190776/b87141d2-e488-11e4-8b45-555b9a8c82d2.png)

**Comment by JonasDoebertin** [comment]
56727ce3cdedab94a4fa7eea0db2c50907ff341b just added support for inline HTML. Could you give it a spin and see if the current styles works out for you?

**Comment by medienbaecker** [comment]
Super awesome! Highlighting the HTML tags is a superb idea. Now me and my client can add **all** the sup's and br's we want. Thank you!

**Comment by JonasDoebertin** [comment]
You're very welcome! :grinning:
