### ISSUE TITLE
Feature Request: Hiding markdown

### ISSUE THREAD

**Issue by bcartier** [JonasDoebertin/kirby-visual-markdown#2]
Although I think this is a great way to ease some clients into using markdown, I'd love to see an option for hiding the markdown in the live preview. Unfortunately, many clients just don't want to have anything to do with even simple Markdown in their content. 

The icing on the cake would be the ability to insert and align an image (with preview).

**Comment by JonasDoebertin** [comment]
If you want to hide the markdown completely, you should have a look at another editor extension I create together with one of my clients: [Kirby WYSIWYG Editor Field](https://github.com/storypioneers/kirby-wysiwyg).

It's far from perfect but I guess it's a good starting point.
