### ISSUE TITLE
cmd+A doesn’t work as expected on OSX

### ISSUE THREAD

**Issue by tweh** [JonasDoebertin/kirby-visual-markdown#27]
Hi,

on OS X the shortcut `cmd`+`A` usually selects all the text, but this doesn’t work in the markdown field, instead a link is created.
 Can this be changed?

**Comment by JonasDoebertin** [comment]
You should have a look at `assets/js/visualmarkdowneditor.js` starting from line 196. This is where all hotkeys are defined.

FYI, I have an option planned where you can change or disable any hotkey from your blueprints. Don't know when I'm able to add it though.

**Comment by tweh** [comment]
Thanks. I’ll take a look at it …

You may close this issue but in my opinion it’s not a good idea to overwrite the few standard shortcuts (i.e. `cmd` (Mac) or `ctrl` (Win) + `A`, `S`, `C`, `V`, or `X`), which behave the same in nearly all programs.

**Comment by JonasDoebertin** [comment]
I opened a dedicated issue for finding new keymaps for the shortcuts. See #29.
