### ISSUE TITLE
Can't paste since I upgraded to Kirby 2.1.0 final

### ISSUE THREAD

**Issue by malvese** [JonasDoebertin/kirby-visual-markdown#31]
I can no longer paste anything in the `textarea`, nor drag and drop text from another app or window, nothing is output.
I use an up-to-date kirby-visual-markdown, on the master branch.

**Comment by JonasDoebertin** [comment]
I just did a quick check:

With the new _Kirby 2.1 release_ and the latest stable _Visual Markdown Editor release_ in place, I can copy/past from/into regular textareas as well as the Visual Markdown Editor just fine.

**Comment by JonasDoebertin** [comment]
Also dragging and dropping text works just fine for both textareas and the Visual Markdown Editor field.

Do you have any other panel plugin/extensions active? Have you checked the console for potential JS errors?

**Comment by malvese** [comment]
You are right, the visual editor was not the culprit, really sorry for the false alarm!
Since the updates for some reason shortcuts and even the right click menu were hijacked on that site. I had to log out and cleared the cache, it works again now. Thank you for checking and sorry again.
