### ISSUE TITLE
Question - Image / Link

### ISSUE THREAD

**Issue by ghost** [JonasDoebertin/kirby-visual-markdown#34]
How do i link via panel and visual markdown editor an image thumbnail (generated by image tag) with full image (via link tag, i suppose?). Both images are loaded and visible in panel editor.

i try something like [ <code>![image_alt]</code><code>(image:url_thumbnail_image.jpg)</code> ] <code>(link:url_full_image.jpg)</code>
it does not work.

**Comment by JonasDoebertin** [comment]
I guess this question is not directly related to Visual Markdown Editor, as it works the same as in a regular stock textarea text input.

You should have a look at [the Kirby docs](http://getkirby.com/docs/content/text#images) to see how to create linked images using the _image_ kirbytext tag.

**Comment by ghost** [comment]
Thanks!
