### ISSUE TITLE
Can't write in Fullscreen on pages with multiple markdown fields

### ISSUE THREAD

**Issue by xu-chris** [JonasDoebertin/kirby-visual-markdown#4]
**Bug:** Can't write in fullscreen mode on pages with multiple markdown fields.
**Version:** 1.0, 1.0.1
**Tested browsers:** Safari (doesn't work except for making a paragraph by hitting enter...crazy (just in v. 1.0)), Chrome (works just in v. 1.0)

Possible solution: Maybe you have to set the cursor and focus right?

**Comment by JonasDoebertin** [comment]
I just fixed the issue reported in #5.

Also, Safari doesn't allow keyboard input while in fullscreen. So there's no chance to get it to work there (only solution is to hide the fullscreen mode button on Safari).

I can't find any problems with typing in fullscreen mode with Chrome, though.

**Comment by xu-chris** [comment]
It's a bug in Safari I think. Chrome works with fixes in #5.
