### ISSUE TITLE
Required: true breaks the panel when field is left empty

### ISSUE THREAD

**Issue by FabianSperrle** [JonasDoebertin/kirby-visual-markdown#42]
Adding `required: true` to the markdown field is tricky right now: When there is text in the field, no problems occur. However, when the input is left blank - and this is where `required` would become important - the field breaks the panel JS and prevents the page from being saved:

```

An invalid form control with name='' is not focusable. (index):1 
An invalid form control with name='text' is not focusable. (index):1 
```

**Comment by JonasDoebertin** [comment]
Thanks for letting me know! I'll have a look at it.

**Comment by JonasDoebertin** [comment]
The problem was that Chrome is attempting to validate the underlying textarea element which has been hidden in CSS. That is preventing it from showing its validation warning message, and it's alerting you of this fact.

This is fixed now in the `develop` branch.
