### ISSUE TITLE
switching Heading type should replace current header

### ISSUE THREAD

**Issue by mcbrwr** [JonasDoebertin/kirby-visual-markdown#44]
First of all: Great plugin! Thanks!
Second of all: If I can make some time I'll see if I can resolve this myself and post a pull-request.

The issue: When I use a heading and then press the other heading button, the # marks are not replaced but added, so I get something like this: 

```
## ### Heading switched from h2 to h3
```

**Comment by JonasDoebertin** [comment]
Sounds reasonable. Great idea, I'll implement this as soon as possible!

Thanks 👍

**Comment by JonasDoebertin** [comment]
This has been added to the `develop` branch.

**Comment by mcbrwr** [comment]
thanks! I'll give it a go soon :-)
