### ISSUE TITLE
Visual Markdown as editor in the Panel

### ISSUE THREAD

**Issue by markhaehnel** [JonasDoebertin/kirby-visual-markdown#46]
How can i set Visual Markdown the default editor in the Panel when editing posts?
The instructions in the README didn't help me a lot.
I don't know which blueprint i have to edit.

Hope you can give me a short summary of steps! :grin:

**Comment by JonasDoebertin** [comment]
A single blueprint is always related to a single "page type" or "page template". To replace the default textarea and use the Visual Markdown Editor everywhere, you can just replace `type: textarea` with `type: markdown` in all your blueprints.

Of course you can also choose to use the Editor only at some places. Whenever you have a `type: textarea` that also has `buttons: false` set, you'd probably want to keep this.
