### ISSUE TITLE
Formatting Tables

### ISSUE THREAD

**Issue by xu-chris** [JonasDoebertin/kirby-visual-markdown#48]
Hi!

Maybe this is too much for you but I've found this very cool idea and solution for adding tables:
https://github.com/yabwe/medium-editor-tables

Maybe this helps you to add even more awesomeness to your field! :-)

**Comment by JonasDoebertin** [comment]
I think with the way Visual Markdown Editor is built, adding tables is not an option right now. The underlying code editor CodeMirror isn't meant to add rich content, like tables. I don't see a way to make this work (other then rewriting the whole editor from scratch, without CodeMirror as base).

**Comment by JonasDoebertin** [comment]
Yeah, I thought about this again and came to the conclusion that I won't be adding any table-related features as it's just not doable with a reasonable amount of work with CodeMirror as a base.

**Comment by rmngrc** [comment]
Hi @JonasDoebertin 

First things first, this is an awesome field which is a great addition to the kirby ecosystem.
That being said, I don't think it's impossible to add support for tables, these guys already made this editor based in CodeMirror: https://georgeosddev.github.io/markdown-edit/

Cheers,
