### ISSUE TITLE
Unsaved changes show up after reloading

### ISSUE THREAD

**Issue by dennisfrank** [JonasDoebertin/kirby-visual-markdown#49]
I am currently testing the editor and stumbled over following issue:

Any **unsaved** changes in a markdown field show up again (and again) after reloading or closing and reopening of an entry page. Keep in mind that the entry did not get saved.

I made a little [screencast](http://cl.ly/0J253h290z3c). 

Any ideas?

**Comment by JonasDoebertin** [comment]
This is related to a feature that got introduced to the Panel a while ago: If you do some changes to any field and leave the page (by using the panel menu or by going back) these changes are saved and reapplied when you come back to the page. You even get a little info right above the _Save_ button saying _You have unsaved changes!_ with an option to discard those.

This happens to every other text or textarea (and even my JS-driven selector field), too.

**Comment by dennisfrank** [comment]
Oops. You’re so right, Jonas. Thanks for pointing this out.

**Comment by JonasDoebertin** [comment]
You're absolutely welcome! 😉
