### ISSUE TITLE
Don't get right field for fullscreen on pages with multiple markdown fields

### ISSUE THREAD

**Issue by xu-chris** [JonasDoebertin/kirby-visual-markdown#5]

**Comment by xu-chris** [comment]
**Bug:** I don't get the right field for fullscreen on pages with multiple markdown fields. For example: if I want to edit the first or the second of three markdown fields, it always opens the last one. And I can't select or positioning the cursor in the fullscreen window (in addition to #4 which doesn't work for all browsers).
**Version:** 1.0.1
**Tested browsers:** Safari, Chrome

**Comment by JonasDoebertin** [comment]
Just fixed this with the latest `develop` version.

@servicethinker Would you mind checking it out and report any further issues if you find any?

**Comment by xu-chris** [comment]
Works fine now in both. :-) #4 seems like a bug in Safari. I'll report that to Apple.
