### ISSUE TITLE
Change field name to be more adequate

### ISSUE THREAD

**Issue by JonasDoebertin** [JonasDoebertin/kirby-visual-markdown#52]
As some of you already pointed out in the past, the name "markdown" as used in your blueprints with `type: markdown` is a bit too generic.

With one of the next releases, I want to change this. However, I need your help with choosing the new name. **So, here's a quick poll: What do you think should be used?**
- `visualmarkdown`
- `visualeditor`
- `visualmarkdowneditor`

Of course this change will require you to reinstall Visual Markdown Editor instead of simply updating your submodule. But as this will take only one or two minutes longer then usual, I think it is a reasonable change.

**Comment by MathiasGmeiner** [comment]
+1 for `visualmarkdown` from me.

**Comment by malvese** [comment]
My vote for visualmarkdown. Or any made-up name that is not generic: visualmark, visualtext, whatever. visualmarkdown sounds good though.

**Comment by JonasDoebertin** [comment]
I guess `visualmarkdown` it is.

**Comment by ghost** [comment]
I would favour visualmarkdown as the field name too. :+1:

**Comment by alkinkasap** [comment]
+1  for `visualmarkdown` but keep markdown as field name for some of next releases as some people like me will forget to change :)

**Comment by JonasDoebertin** [comment]
The field will finally be renamed to `visualmarkdown` with the next release 🎉
