### ISSUE TITLE
Slightly alter fixed toolbar nehaviour to work with fixed top save button

### ISSUE THREAD

**Issue by shoesforindustry** [JonasDoebertin/kirby-visual-markdown#55]
It would be nice for the fixed toolbar to work with the [fixed position save button](https://gist.github.com/flokosiol/c030008acd31b2916036)

This can do that, it basically just drops the toolbar below the main black Kirby one...

``` CSS
.markdownfield-wrapper .visualmarkdown-toolbar-fixed {
...
    top: 3em;
...
```

Also I think I'd like my main text to stand out a little bit so I always change the font size to 1.45 or 1.5

``` CSS
.cm-s-visualmarkdown {
    font: 1.45em/1.45 monospace;
....
```

**Comment by shoesforindustry** [comment]
Actually may also be worth adding a bit of shadow when in fixed position, so you can see text 'going under'?

``` css
.markdownfield-wrapper .visualmarkdown-toolbar-fixed {
    box-shadow: 0 8px 6px -6px #aaaaaa;
...
```

![screen shot 2015-08-29 at 10 07 27](https://cloud.githubusercontent.com/assets/2102743/9561278/1250d11a-4e36-11e5-8c30-4927e64b4830.png)

![screen shot 2015-08-29 at 10 10 49](https://cloud.githubusercontent.com/assets/2102743/9561283/4b67765c-4e36-11e5-9a05-9284714367e5.png)

**Comment by JonasDoebertin** [comment]
As Bastian told us in the forums, the next version of the panel will include a redesigned/reworked save button. I'll make sure the sticky toolbar will works with the changes.

Right now, I guess you should just add the few lines of CSS your own, eg. via the custom panel stylesheet, to make it work with the save button modification.
