### ISSUE TITLE
Kirby 2.2 compatibility 

### ISSUE THREAD

**Issue by ghost** [JonasDoebertin/kirby-visual-markdown#57]
:bug: I'm running a Kirby 2.2 beta (based on the nighlty) site together with the kirby visual markdown plugin and it's not working. All I get is a two line textarea and the buttons as a bold title and shortcut. 

It works fine for me when I use it with the latest stable version of Kirby. 

I see there was someone else before me reporting this in issue #36. 

If you have any idea where to start hunting the problem down I will have a look myself.

Update: I had a look at it real quick and it non of the assets are loaded anymore. I hardcoded them in and the field works. Looks like they are not picked up by the panel anymore. Resulting in the unstyled textarea. On top there are two missing files. The form.css and form.js are missing. I guess they would normally hold the custom field assets too. 

Thank you.

**Comment by ghost** [comment]
I checked a little bit more what could be the problem. If you look at the panel routes file end, you will see two routes for the mentioned form .css/.js and they just don't respond with something else than 404 which then results in the both variables being empty too.

**Comment by JonasDoebertin** [comment]
Hmm. I just did a test run on three different projects using the latest Kirby 2.2 nightly version and Visual Markdown Editor works just fine with all of them.

**Comment by ghost** [comment]
I tested more as well. I ran on a df server with PHP5.6.12 and it worked like a charm. On my Mac I tested with the PHP5.6.14 build in dev server and it does not work. I guess that's the problem. Not running it with the PHP server.

**Comment by JonasDoebertin** [comment]
Seems to be related to getkirby/panel#605 if you ask me.

**Comment by ghost** [comment]
Yes that should be the problem spot. Thank you for your help and linking the issue back to Kirby.
