### ISSUE TITLE
Fullscreen Button disappeared

### ISSUE THREAD

**Issue by JanCK** [JonasDoebertin/kirby-visual-markdown#58]
That is it. Even after submodule update nothing changed.

![bildschirmfoto 2015-11-05 um 16 19 28](https://cloud.githubusercontent.com/assets/1202019/10972349/0e91f5a8-83d9-11e5-980a-7fe13b7b699b.jpg)

**Comment by JonasDoebertin** [comment]
Are you running Safari? the fullscreen button is hidden on Safari. On purpose.

Safari doesn't allow keyboard input in fullscreen mode, thus it is useless. This is true even for Safari 9.

**Comment by JanCK** [comment]
Stupid Safari! 
Thnx
