### ISSUE TITLE
Make white space clickable to add text

### ISSUE THREAD

**Issue by xu-chris** [JonasDoebertin/kirby-visual-markdown#6]
Because of the (beautiful) padding of `CodeMirror` it's more difficult to click into the textfield. Just make the whole thing clickable. Possible solution: instead of setting to the `CodeMirror` the padding, set it to `CodeMirror-scroll` - that works in my quick and dirty prototype in Safari. This doesn't work so well in the fullscreen mode but in the normal mode.

![bildschirmfoto 2015-04-01 um 12 26 58](https://cloud.githubusercontent.com/assets/980778/6939209/90394cca-d86a-11e4-839e-5bf0a5347935.png)

**Comment by JonasDoebertin** [comment]
@servicethinker Thanks for your valuable insights!

I'll have a look how we can improve the padding behavior.

**Comment by JonasDoebertin** [comment]
Should be done with 70ef3208ba717a1ebc3519ecf67163ac52cd653f.

**Comment by xu-chris** [comment]
It works great now! Thanks for this very quick fix!
