### ISSUE TITLE
The VM custom fields don't seem to be appearing as they should in K2.2

### ISSUE THREAD

**Issue by shoesforindustry** [JonasDoebertin/kirby-visual-markdown#60]
The VM custom fields don't seem to be appearing as they should in K2.2 panel, instead I'm getting a default single line text area?
They worked before the Kirby upgrade, on the off chance I tried the dev version of the plugin, but the same?

Any ideas?

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Did you use the master-branche or the developers-branche?

The master-branche causes errors, in combination with the modal.

The developers-branche causes the error you describe (no buttons, only two lines of text visible).

The error above is described here; https://github.com/JonasDoebertin/kirby-visual-markdown/issues/61

In the third comment on that page.

**Comment by JonasDoebertin** [comment]
Let's keep everything together over at #61.

**Comment by shoesforindustry** [comment]
Sorry, I'd missed that post, but yes the dev branch and the same two line - no buttons error.
