### ISSUE TITLE
Duplicated Toolbar after opening a modal view and canceling the modal view directly

### ISSUE THREAD

**Issue by jensfranke** [JonasDoebertin/kirby-visual-markdown#68]
![bildschirmfoto 2015-12-01 um 21 56 31](https://cloud.githubusercontent.com/assets/595504/11513980/7e95f348-9876-11e5-8bfd-d0f1d2d5019e.png)

**Comment by JonasDoebertin** [comment]
Are you sure you're using the latest available version? This issue should have been fixed with the last update. See #61.

**Comment by jensfranke** [comment]
Sorry, my fault. Works fine with the latest version. Thanks for the hint!

**Comment by JonasDoebertin** [comment]
You're welcome!
