### ISSUE TITLE
Spell Checker Fails

### ISSUE THREAD

**Issue by shoesforindustry** [JonasDoebertin/kirby-visual-markdown#69]
In Firefox Mac, there is no ''right-click' spell checker when using this field, reverting to textarea the spell checker is back?

**Comment by JonasDoebertin** [comment]
Isn't this the normal behavior? It's the same for me using Chrome with any "contentEditable" powered editor/input.

Spell check does work on regular textareas only, doesn't it?

**Comment by shoesforindustry** [comment]
I did think it used to work? I'm sure it did with other editors?

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
It's an interesting issue; the default WYSIWYG editor in Wordpress has spell-check, but something like CKEditor not - http://ckeditor.com/demo

**Comment by shoesforindustry** [comment]
Sadly yes, I love Visual Markdown, but my spelling is so bad...

**Comment by JonasDoebertin** [comment]
Hmmm. I guess this is something I have to investigate further. I'll leave this open for now.

**Comment by shoesforindustry** [comment]
Some editors seems to have their own spell checker, but I think using the default one is probably best?
I leave it in your capable hands...

**Comment by JonasDoebertin** [comment]
Just did a quick search and came to the following conclusion:
- Browser based spell checking does in fact work on input and `contentEditable` elements
- CodeMirror (what Visual Markdown Editor is based on) doesn't use `contentEditable` elements at all so there's no way of getting browser based spell checking to work
- One could integrate a custom, JS based, spell checking library with CodeMirror using overlays, but that would, probably, affect performance and file size massively

Related topic: https://github.com/codemirror/CodeMirror/issues/1017

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Strange thing is that the manual refers to a spell-check option;

http://codemirror.net/1/manual.html

```
disableSpellcheck

Should the editor disable spell-checking on browsers that support it (Firefox 2+).
Default is true, since for most code spell-checking is useless.
Can be changed with the setSpellCheck(on) method.
```

I tried this option (setSpellCheck(on)) but it didn't work out for me.

There are also some plugins;
- http://nextstepwebs.github.io/codemirror-spell-checker/
- http://stackoverflow.com/questions/12343922/codemirror-with-spell-checker

**Comment by JonasDoebertin** [comment]
The manual link you posted is really outdated. It refers to an old version of CodeMirror from a time when it was using a `contentEditable` element.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Okay - I will not digg in it further more.

The most easy thing is to add a code-toggle button to the toolbar, which makes the `textarea` visible.

![image](https://cloud.githubusercontent.com/assets/15701574/11653761/bf62ce08-9da0-11e5-9a1d-990a6ca8f4fa.png)

This one shows the typo's you made - so you can correct them and hide the raw-code by clicking on the button again.

Don't know this is helpfull...

**Comment by JonasDoebertin** [comment]
Seems like there is no solution to use the browsers default spell check with CodeMirror. Closing this for now.
