### ISSUE TITLE
Incorrect kirbytag highlighting

### ISSUE THREAD

**Issue by Jayshua** [JonasDoebertin/kirby-visual-markdown#75]
There appears to be two issues with the kirbytag highlighting feature. First, it doesn't highlight tags with dashes in the name. Second, a tag with no arguments breaks the highlighting. Here's an example:

![example](https://cloud.githubusercontent.com/assets/1654103/12246414/fbaff848-b873-11e5-85f2-0d0a5a96de65.png)

**Comment by malvese** [comment]
Same if you use custom Kirbytext without `:`, like the [columns plugin](https://getkirby.com/blog/columns-in-kirbytext) from the Docs:

```
(columns…)
Text here
(…columns)
```

But this may be hard to work around, because how can you guess if something like `(Hello…)` is Kirbytext or not? ;)

**Comment by JonasDoebertin** [comment]
Properly highlighting the cases @Jayshua described should be doable. I'll look into this.

***

```
(columns…)
Text here
(…columns)
```

For this however I don't know. Imho something along the lines of `(well…)` would be matched too. Also, with the way the Kirbytext highlight mode is implemented, looking ahead is possible (to only match a `(well…)` if it's followed by a `(…well)`), but not capable enough to pull this of reliably, I think.

**Comment by Jayshua** [comment]
Just an idea here: Would it be possible to get the registered tags and use them to highlight? Maybe in the PHP and pass an array of them to the JS?

**Comment by JonasDoebertin** [comment]
One should in fact be able to pull this of. Don't know if we really need it though because:

* matching regular Kirbytags works good as it is know (at least with the changes I have in mind to fix your "edge-cases")
* the columns plug-in doesn't use Kirbytags (doesn't register one) at all but uses a custom filter with its own regex.

**Comment by JonasDoebertin** [comment]
Just improved the Kirbytext highlighting to properly match the kinds of tags @Jayshua showed.

![bildschirmfoto 2017-02-04 um 14 46 55](https://cloud.githubusercontent.com/assets/1367270/22618898/e22b3222-eae8-11e6-8d34-2202efc26981.png)

I'll keep matching for the columns plugin on my todo list though.
