### ISSUE TITLE
Neat plugin

### ISSUE THREAD

**Issue by shoesforindustry** [JonasDoebertin/kirby-visual-markdown#8]
All seem to work quite well, very nice, so thank you. 

In develop branch headings are a good addition, some sites may well want to use H1 and H2 headings in their content, but other may well want to specify (probably on a per template basis) to start at a lower level, for example H3 and H4 (having used H1 and H2 already in the site template).

Also maybe the option to turn individual items on/off?

Some extra spacing or margin might be nice ;-) (Firefox/Mac - ordinary release)
[Example of margins](https://owncloud.shoesforindustry.net/index.php/s/Xeu6kZeBRtUaAuo)

Just a thought.

**Comment by JonasDoebertin** [comment]
> In develop branch headings are a good addition, some sites may well want to use H1 and H2 headings in their content, but other may well want to specify (probably on a per template basis) to start at a lower level, for example H3 and H4 (having used H1 and H2 already in the site template).

You actually can specify the heading levels, it's just not documented, yet. You use the options `header1` and `header2` in your blueprints and set them to anything from `#` to `######` to tell the editor which heading levels you'd like to use.

> Also maybe the option to turn individual items on/off?

Nice idea, I'll think about it :)

> Some extra spacing or margin might be nice ;-) (Firefox/Mac - ordinary release)

I don't see this issue in Chrome and Safari. The full screen icon and it's border shouldn't spread out more then the toolbar. I'll double check this.

**Comment by shoesforindustry** [comment]
Mmmm, can’t get to Github at the moment, but I’m seeing the same formatting on Mac/Safari?
It would appear to be caused by using `icon: XXXX` in the blueprint `type:  markdown` elements (a hangover from when we were not using this plugin).

e.g.
  intro: 
    label: Article Intro
    type:  markdown
    required: true
    size:  small
    icon: twitch
Removing this solves the problems.

Might be worth fixing?

As for headers brilliant, as long as the editor icon/label changes to reflect the heading e.g. we don’t want a h1 button producing h3’s ###. We’d want the button to be called h3 as well. I think this is more logical, but I can see how others might want it the other way.

Russ

**Comment by JonasDoebertin** [comment]
> It would appear to be caused by using `icon: XXXX` in the blueprint `type:  markdown` elements (a hangover from when we were not using this plugin).

I must say I forgot about testing custom icons for this editor field. I guess I'll have to disable these, so that the `icon: youricon` doesn't have an effect on the editor, for the time being.

But I think a custom icon is a feature we might need to support, though? Styling could be similar to your screenshot, but with fixed margins/paddings. What do you think?

---

> As for headers brilliant, as long as the editor icon/label changes to reflect the heading e.g. we don’t want a h1 button producing h3’s ###. We’d want the button to be called h3 as well. I think this is more logical, but I can see how others might want it the other way.

I'm not sure. I think it would be more semantic, in the context of the markdown content, to call it _H1_ and _H2_ all the time. Think of it as _"Headline"_ and _"Sub Headline"_. The terms _H1_ and _H2_ may be misleading though (as users might think of them as `<h1>` and `<h2>` and, semantically, this doesn't have to be true).

Unfortunately, AFAIK, Font-Awesome (which the panel uses for icons) doesn't have any proper icons for headlines and sub headlines. I'd just use those instead.

**Comment by JonasDoebertin** [comment]
> You actually can specify the heading levels, it's just not documented, yet. You use the options `header1` and `header2` in your blueprints and set them to anything from `#` to `######` to tell the editor which heading levels you'd like to use.

And of course, this is just plain wrong. Sorry for that! You'd have to set the `header1` and `header2` values to anything from `h1` to `h6` in your blueprints.

**Comment by shoesforindustry** [comment]
Sadly not for most of our users, they are all aware that their sites use h1 and h2 in the template to they expect to use h3/h4 etc. in content.

Having a button that is marked h1 that produces a h3 heading in markdown, just seem plain wrong to me!
Markdown users, when trained a bit, are quite savvy when it comes to this ;-)
From a personal point of view, if this were the case I’d be wanting to be able to turn it off. In fact I’ve gone back to the release version of your plugin (rather than the develop version) for that very h1/h2 reason. However, I can see that some people might want it this want it this way, so a way to set the label and the content it produces would be the best solution? If so just use text with a box for the buttons, no need to worry about icons?

I do think you will have to adjust your code to allow for icons/no icons if they are set in the blueprint. I guess it is only the right margin you need to worry about, I guess it’s CSS so use em? Also maybe get the text left margin to line up with the icons, so it looks nice and neat?

I’ve got to dash to a meeting now, but will be online later.

Russ

**Comment by JonasDoebertin** [comment]
Just letting you know: I just implemented proper styles for fields with icons and changed the heading icons so they indicate the level. It better this way until there is an even nicer solution.
