### ISSUE TITLE
tabindex="-1" on the toolbar

### ISSUE THREAD

**Issue by AhoyLemon** [JonasDoebertin/kirby-visual-markdown#84]
Hi there,

I was just editing a page with my hands off the mouse, and when I tabbed over to the markdown field, it stopped on the H1 button, an additional tab took me to H2.

I feel like intended result here would be to have these buttons ignored by tab, because the premise of visual markdown means those links aren't meant for that kind of accessibility.

Do you think it would be worth doing to add `tabindex="-1"` to all the links in the toolbar, to avoid this from happening. I'd be happy to put in the PR myself, just wanted to check with you before doing that.

Also, thanks a lot for the plug-in. It's been super useful for me.

**Comment by JonasDoebertin** [comment]
Seems like a logical step to add the attributes. Feel free to send a PR. 👍

**Comment by JonasDoebertin** [comment]
Implemented with 76b269b1c4d83836bbbf758249e0c232afc523dd
