### ISSUE TITLE
Request: Add optional buttons for all headings

### ISSUE THREAD

**Issue by heyallan** [JonasDoebertin/kirby-visual-markdown#90]
**Add optional buttons for all headings** `h1` to `h6`

**Also:** Don't use `H` character for headings in button label because it only makes sense for english speakers.

**Use 'A' character instead:**

``` html
 <button>A<sup>1</sup><button>
```

**Output would look like this:**

![screen shot 2016-04-19 at 8 16 42 pm](https://cloud.githubusercontent.com/assets/1783777/14661593/16fcdfe4-066c-11e6-8790-cff946a41449.png)

**Comment by Andi-Lo** [comment]
I don't think this change is necessary.

However you can change the icon yourself if you change in: site/fields/markdown/assets/js/visualmarkdowneditor.js on line 198: `classname: 'fa fa-font'`

Because font-awesome does not provide any other fonts (like A1, A2, A3) you would run into trouble there. Check the full list here of supported icons here: http://fontawesome.io/icons/

**Comment by heyallan** [comment]
1. Hacking the plugin is not a solution
2. Using font-awesome is not the only way to achieve things

I still think making the toolbar more modular is a good idea.

**Comment by coderica** [comment]
I accidentally created a feature request much along the same lines before seeing this one. I don't agree with the redesign but I do fully agree with adding the other 4 headers. This, along with adding code snippets, seems like a simple and obvious next step, as they are the two main things keeping this plugin from being a complete markdown editor.

The attached photo is of github's comment editor - they include the code block button and I like how they handle making more room with the header dropdown menu. The icon github uses would not only solve Allan's design problem, but makes more sense to people who are not familiar with markdown and are used to something like ms word (which is likely if a developer is installing a visual editor for the content writer, as it is in my case).

<img width="643" alt="screen shot 2016-04-26 at 4 42 20 pm" src="https://cloud.githubusercontent.com/assets/10325222/14822315/7c3a29ea-0bce-11e6-957d-e8604fd922a0.png">

**Comment by JonasDoebertin** [comment]
Implementing anything along the lines of @coderica's suggestion might be an option for a later release.
