### ISSUE TITLE
Bullets aren't showing up.

### ISSUE THREAD

**Issue by Jlirving** [JonasDoebertin/kirby-visual-markdown#95]
Hi there, 

The editor has been working fine with everything except bullets. They were originally working fine however they don't seem to be working at all any more.

Does anyone else have this issue?

Thanks.

**Comment by JonasDoebertin** [comment]
Is this still an issue for you?

**Comment by Jlirving** [comment]
Hey mate,

No it's not, what I actually had to change was the indent for the bullets.
The default indent was working off of a standard margin but as soon as I
started playing around with containers for content they would stay in the
same spot so it looked at of the indent was gone.

Jack Irving
M: 0410 990 696
