### ISSUE TITLE
Installed but not working?

### ISSUE THREAD

**Issue by cavynmaicl** [JonasDoebertin/kirby-visual-markdown#96]
I've installed everything as per your directions, and made the template adjustments and the fields are showing up in the panel interface, but the text isn't rendering out correctly on the site. Any idea why that might be happening?

**Comment by Thiousi** [comment]
What does 'not rendering out correctly' mean?

**Comment by JonasDoebertin** [comment]
Is this still an issue for you?

**Comment by cavynmaicl** [comment]
Nope. Thanks.
